# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = nano328
# BOARD_TAG    = uno

# CFLAGS_STD = -std=gnu99 -fno-threadsafe-statics -flto
include /usr/share/arduino/Arduino.mk


